### PR TITLE
Update api response for locations

### PR DESCRIPTION
**Pull request by dbalatero**
Sorry for the cleanup commits – it helped me read the code to reformat it.

This updates the `locations.json` response to sort by distance.

Trello: https://trello.com/c/WyiJc2Vf/184-locations-json-api-issues

/cc @ezwelty @somerandomsequence

### CODE REVIEW

**Comment by ezwelty** [comment]
Thanks. One issue I see is that type filter (&t=) is now not enforced since you're not considering the 'sort' field, which I think is how Caleb stuck the filtered types on top of the stack. For example:

http://localhost:3100/api/0.2/locations.json?api_key=*****&locale=en&muni=1&nelat=40.00156699355835&nelng=-105.27841178077733&swlat=40.00084067298544&swlng=-105.28098670143163&t=198&lat=40&lng=-105.2

v.s. 

https://fallingfruit.org/api/0.2/locations.json?api_key=*****&locale=en&muni=1&nelat=40.00156699355835&nelng=-105.27841178077733&swlat=40.00084067298544&swlng=-105.28098670143163&t=198&lat=40&lng=-105.2

**Comment by dbalatero** [comment]
Ok - my patch does the following:

`ORDER BY distance asc, sort asc`.

I think we could fix what you're saying by doing `ORDER BY sort asc, distance asc` - e.g. sort by `t`, but use distance as a secondary sort.

**Comment by dbalatero** [comment]
> BTW, would you prefer I start dropping issues into Github issues? Say, the list of things I brought attention to here: falling-fruit/falling-fruit-mobile#4 (comment)

I filed them as Trello cards since that's what you seemed to be using for project management and I didn't want to fragment things. Trello works for me!

**Comment by dbalatero** [comment]
Fixed the sort discrepancy here: 💚 e8058bb

**Comment by ezwelty** [comment]
We may be well served by making our development more public, so how about we try out using GitHub issues instead of Trello for a bit? Here's another issue I just found with locations.json:
https://github.com/falling-fruit/falling-fruit/issues/14

**Comment by dbalatero** [comment]
Okay cool. I'll move any issues I start on Trello back over to GH.

**Pull request merged**
