### PR TITLE
Return title from locations.show/list

### PR DESCRIPTION
**Pull request by dbalatero**
@ezwelty This adds a `title` column to the response for `locations.show` and `locations.list`.

This is the API side of the work for #17.

I'm curious what UI elements need to get updated on the client-side to reflect this new title field? Could you point me in the right direction w/ a few screenshots? Or if it's faster for you to make the new edits, open a PR against the `new-api` branch in `falling-fruit-mobile`?

Thanks!

### CODE REVIEW

**Comment by ezwelty** [comment]
@dbalatero Must be a bug, as this breaks location/{id}.json with an empty response error.

http://localhost:3100/api/0.2/locations/3383.json?api_key=EEQRBBUB

**Comment by dbalatero** [comment]
@ezwelty sorry about that, I was moving too fast and should have tested that route :( thanks for the catch, I tested it and it seems all good now.

**Comment by dbalatero** [comment]
@ezwelty Still could use a bit of feedback on:

> I'm curious what UI elements need to get updated on the client-side to reflect this new title field? 

thanks!

**Comment by ezwelty** [comment]
@dbalatero Since view_location will actually need to build a long form type list ("Common name [Scientific name]"), the title is currently only used here:

https://github.com/falling-fruit/falling-fruit-mobile/blob/master/src/jade/partials/list.jade#L8

**Comment by ezwelty** [comment]
@dbalatero In response to https://github.com/falling-fruit/falling-fruit-mobile/pull/7#issue-211930657: either titles from locations.json need to be locale specific or we revert to generating the titles for the list client-side.

**Pull request merged**
